export const REQUIRED_FOR_SEND = Object.freeze([
  "OPENAI_API_KEY",
  "RESEND_API_KEY",
  "DIGEST_FROM_EMAIL",
  "DIGEST_TO_EMAIL",
  "FEEDBIN_EMAIL",
  "FEEDBIN_PASSWORD"
]);

export const REQUIRED_FOR_YOUTUBE_SYNC = Object.freeze([
  "YOUTUBE_CLIENT_ID",
  "YOUTUBE_CLIENT_SECRET",
  "YOUTUBE_REFRESH_TOKEN"
]);

export const OVERCAST_OPML_SOURCES = Object.freeze([
  "OVERCAST_OPML_BASE64",
  "OVERCAST_OPML",
  "OVERCAST_OPML_PATH"
]);

// Repository variables that the scheduled workflow must forward to Node.
export const WORKFLOW_VARIABLES = Object.freeze([
  "OPENAI_MODEL",
  "OPENAI_EMBEDDING_MODEL",
  "USE_EMBEDDINGS",
  "AI_MAX_CLUSTERS",
  "AI_SUMMARIZE_SINGLE_ARTICLES",
  "AI_CONCURRENCY",
  "FETCH_OG_IMAGES",
  "IMAGE_CONCURRENCY",
  "FETCH_SPONSORED_CHECKS",
  "SPONSORED_CHECK_CONCURRENCY",
  "FEED_CONCURRENCY",
  "FEED_FETCH_ATTEMPTS",
  "FEED_FETCH_TIMEOUT_MS",
  "FEED_RETRY_BASE_DELAY_MS",
  "FEED_RETRY_JITTER_MS",
  "FEED_USER_AGENT",
  "FEEDBIN_PER_PAGE",
  "FEEDBIN_SYNC_SUBSCRIPTIONS",
  "FEEDBIN_SYNC_EXTRA_TITLES",
  "FEEDBIN_SYNC_ATTEMPTS",
  "FEEDBIN_SYNC_TIMEOUT_MS",
  "FEEDBIN_PREFER_FOR_BACKFILLS",
  "FEEDBIN_BACKFILL_AFTER_HOURS",
  "OVERCAST_SYNC_SUBSCRIPTIONS",
  "OVERCAST_TOPIC",
  "OVERCAST_MAX_SUBSCRIPTIONS",
  "OVERCAST_MAX_EPISODES_PER_FEED",
  "OVERCAST_OPML_ENCRYPTED_PATH",
  "OVERCAST_SKIP_UNAVAILABLE",
  "OVERCAST_CHECK_CONCURRENCY",
  "OVERCAST_CHECK_TIMEOUT_MS",
  "YOUTUBE_SYNC_SUBSCRIPTIONS",
  "YOUTUBE_SYNC_REQUIRED",
  "YOUTUBE_TOPIC",
  "YOUTUBE_MAX_SUBSCRIPTIONS",
  "YOUTUBE_SKIP_UNAVAILABLE",
  "YOUTUBE_CHECK_CONCURRENCY",
  "YOUTUBE_CHECK_TIMEOUT_MS",
  "VIDEO_LITE_URL_TEMPLATE",
  "SUBSTACK_ARCHIVE_LIMIT",
  "ALLOW_PARTIAL_DIGEST_SEND",
  "CLUSTER_THRESHOLD",
  "EMBEDDING_CLUSTER_THRESHOLD",
  "CLUSTER_CROSS_SOURCE_STRONG_SEMANTIC_THRESHOLD",
  "CLUSTER_CROSS_SOURCE_SEMANTIC_THRESHOLD",
  "CLUSTER_CROSS_SOURCE_PHRASE_SEMANTIC_THRESHOLD",
  "CLUSTER_CROSS_SOURCE_SPARSE_SEMANTIC_THRESHOLD",
  "CLUSTER_SAME_SOURCE_STRONG_SEMANTIC_THRESHOLD",
  "CLUSTER_SAME_SOURCE_SEMANTIC_THRESHOLD",
  "CLUSTER_SAME_SOURCE_PHRASE_SEMANTIC_THRESHOLD",
  "CLUSTER_SAME_SOURCE_LEAD_PHRASE_SEMANTIC_THRESHOLD",
  "CLUSTER_SAME_SOURCE_SPARSE_TERM_WINDOW_MINUTES",
  "CLUSTER_MIN_SHARED_SIGNALS",
  "CLUSTER_MIN_SHARED_PHRASES",
  "CLUSTER_MIN_SHARED_STRONG_PHRASES",
  "NO_BROAD_CLUSTER_TOPICS"
]);

export const LOCAL_ONLY_VARIABLES = Object.freeze([
  "SEND_DIGEST",
  "FEEDBIN_API_BASE",
  "FEED_AUDIT_CONCURRENCY",
  "OVERCAST_OPML_PATH",
  "OVERCAST_SUBSCRIPTIONS_PATH",
  "YOUTUBE_OAUTH_PORT",
  "YOUTUBE_SUBSCRIPTIONS_PATH",
  "NO_CROSS_SOURCE_CLUSTER_TOPICS"
]);

export const OPTIONAL_VARIABLES = Object.freeze(
  [...new Set([...WORKFLOW_VARIABLES, ...LOCAL_ONLY_VARIABLES, ...OVERCAST_OPML_SOURCES])].filter(
    (name) =>
      !REQUIRED_FOR_SEND.includes(name) &&
      !REQUIRED_FOR_YOUTUBE_SYNC.includes(name) &&
      !OVERCAST_OPML_SOURCES.includes(name)
  )
);

export function evaluateEnvironment(env = process.env) {
  const youtubeSyncEnabled = env.YOUTUBE_SYNC_SUBSCRIPTIONS === "true";
  const youtubeSyncRequired = env.YOUTUBE_SYNC_REQUIRED === "true";
  const overcastSyncEnabled = env.OVERCAST_SYNC_SUBSCRIPTIONS === "true";
  const required =
    youtubeSyncEnabled && youtubeSyncRequired
      ? [...REQUIRED_FOR_SEND, ...REQUIRED_FOR_YOUTUBE_SYNC]
      : REQUIRED_FOR_SEND;
  const missing = [
    ...required.filter((name) => !env[name]),
    ...(overcastSyncEnabled && !OVERCAST_OPML_SOURCES.some((name) => env[name])
      ? ["one Overcast OPML source"]
      : [])
  ];

  return {
    missing,
    overcastSyncEnabled,
    youtubeSyncEnabled,
    youtubeSyncRequired
  };
}
